services:
  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - app-network
      - db-network
    depends_on:
      - database

  database:
    build: ./database
    restart: on-failure:5
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network

  httpd:
    build: ./http-server
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge

volumes:
  db-data:  