spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: false
    open-in-view: true
  datasource:
    url: ${{ secrets.SPRING_DATASOURCE_URL }}
    username: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
    password: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
    driver-class-name: org.postgresql.Driver
management:
 server:
   add-application-context-header: false
 endpoints:
   web:
     exposure:
       include: health,info,env,metrics,beans,configprops
